alias: ores_discharge2
description: ""
trigger:
  - platform: time
    at: "8:00:00"
condition: []
action:
  - service: switch.turn_off
    target:
      entity_id:
        - switch.ores_bat_demo_sw_bat_charge
    data: {}
  - service: switch.turn_on
    target:
      entity_id:
        - switch.ores_bat_demo_sw_bat_discharge
    data: {}
mode: single
