esphome:
  name: ores-bat-demo
  friendly_name: ORES_Bat_Demo

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "12345678901234567890123456789012345678901234"

ota:
  password: "12345678901234567890123456789012"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ores-Bat-Demo Fallback Hotspot"
    password: "123456789012"

captive_portal:
    
web_server:
  port: 80










switch:
  - platform: gpio
    id: "SW_Bat_Charge"
    pin:
      number: 14
      inverted: False
    name: "SW_Bat_Charge"
    
  - platform: gpio
    id: "SW_Bat_Discharge"
    pin:
      number: 12
      inverted: False
    name: "SW_Bat_Discharge"


sensor:
  - platform: adc
    id: "Bat_Voltage"
    icon: "mdi:alarm-panel"
    unit_of_measurement: "V"
    attenuation: 11dB
    accuracy_decimals: 2
    pin: 34
    name: "Bat_Voltage"
    update_interval: 0.1s
    raw: True
    filters:
      - multiply: 0.00387
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
    on_value_range:
      - below: 10.5
        then:
          - logger.log: "Low voltage"
          - switch.turn_off: SW_Bat_Discharge
      - above: 15.0
        then:
          - logger.log: "High voltage"
          - switch.turn_off: SW_Bat_Charge

  - platform: adc
    id: "Bat_Current"
    icon: "mdi:alarm-panel"
    unit_of_measurement: "A"
    attenuation: 11dB
    accuracy_decimals: 2
    pin: 35
    name: "Bat_Current"
    update_interval: 0.1s
    raw: True
    filters:
      - lambda: return (x - 1930) * (12.5f / 2048);
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10




