esphome:
  name: ores-cam-demo
  friendly_name: ORES_CAM_Demo

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WIQ37VMDiuhqMbCTNp158KJ9ntcW6pYczBwaE4gE8Eo="

ota:
  - platform: esphome
    password: "4e8d19b2b88d86fbaa950faeb939d8a9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ores-Cam-Demo Fallback Hotspot"
    password: "OInLf0uCVXGv"

captive_portal:
    
web_server: 
  port: 80

# Example configuration entry
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: My Camera
  # ...



